### ISSUE TITLE
.aide directory structure

### ISSUE THREAD

**Issue by Darshan10298** [Xstar97/Navigation-Drawer-Example#1]
Hey, Hello @XStar97
Even I am using AIDE for making apps and loved your tutorial but I have one issue...
I manually downloaded the m2repository.zip and added the dependency after extracting the zip in .aide folder but AIDE cannot catch that!
Can you plzz give or show me the Directory Structure of Libraries in .aide folder :)

**Comment by Xstar97** [comment]
Hi, thanks for using my tutorial!
Can you tell me what libraries & versions you are trying to use & also are there any errors?

**Comment by Xstar97** [comment]
I think I now understand your true question....
Normal libraries
For example....
I used "ask" library in terminal installer x to ask for permission to create folders
"com.vistrav:ask:2.4"
/.aide/maven/com/vistrav/ask/2.4/

Or Google/firebase libraries
/.aide/android_m2repository_r32.zip/m2repository/com/android/support/

/.aide/android_m2repository_r26.zip/m2repository/com/google/firebase/

**Comment by Darshan10298** [comment]
I downloaded android_m2repository_r26.zip
Should I extract it in .aide/

**Comment by Xstar97** [comment]
Well...you should let aide do it for you automatically & just transfer the library versions that you want in each folder...so yea as long as you keep the structure!
the main folder will still need to be named "android_m2repository_r26.zip"
So use the second directory but use this instead..../com/android/
Then make sure to place all libraries in the right folders

**Comment by Darshan10298** [comment]
you mean .aide/android_m2repository_r26.zip/m2repository/com/android/support/design/23.1.1/
right?
Thanks for Quick rply :)

**Comment by Xstar97** [comment]
No....the support libraries are in r32 folder NOT r26....also version 23.4.0 is the most updated version if compiling upto marshmallow

**Comment by Xstar97** [comment]
It will be easier if you let aide do it for you & just add the compile line to the build.gradle....

compile 'com.android.support:design:23.4.0'

**Comment by Darshan10298** [comment]
Having issues wid AIDE, it crashes in between, mostly at 68% when
downloading the Libs...
Reported mayn a times but no Support!
Thats why I manualluy downloaded and extracted in .aide folder and
added dependency but it didn't catch that :(
That's why I asked for folder structure :)
You can give a ScreenShot of dir. structure if u still have it in your Sdcard :)

Thanks for ur Quick Support! :)

**Comment by Xstar97** [comment]
Well obviously I still have the structure since I'm using some of the
support libraries myself... But are you using the latest aide version from
google play?

Your device may not have the storage capacity for aide to download its
dependencies...

Also I already explained the aide structure too...the support libraries are
only found in the r32 folder...

Yea I have some issues myself with aide & it has a crap report
system/support team...never understood a single problem I have....so when I
get my PC fix or buy a new one...I'm only going to use Android studio from
now on..

On Jul 25, 2016 03:24, "Darshan10298" <notifications@github.com> wrote:

Having issues wid AIDE, it crashes in between, mostly at 68% when
downloading the Libs...
Reported mayn a times but no Support!
Thats why I manualluy downloaded and extracted in .aide folder and
added dependency but it didn't catch that :(
That's why I asked for folder structure :)
You can give a ScreenShot of dir. structure if u still have it in your
Sdcard :)

Thanks for ur Quick Support! :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Xstar97/Navigation-Drawer-Example/issues/1#issuecomment-234863913>,
or mute the thread
